### ISSUE TITLE
setpersonshome liefert "fail" zurück

### ISSUE THREAD

**Issue by justselling** [demel42/IPSymconNetatmoSecurity#1]
Der Aufruf für setpersonshome ist gemäß Spec von Netatmo ein "POST" Request. Es wird aber aktuell ein GET Request gesendet. Der Request liefert auch ein "fail" zurück mit dem Vermerk "nodata".

**Comment by demel42** [comment]
sorry, ich habe kein Auge auf meine Issues gehabt. Da ich keine 'Welcome' habe, kann ich das nicht testen. Kannst/willst Du das testen?
Hast Du IP-Symcon im Einsatz oder ein anderes System?

**Comment by demel42** [comment]
ist in der aktuellen version erledigt
